import React, { ReactNode } from "react";
import { Providers } from "@src/redux/provider";
import { Open_Sans } from "next/font/google";
import "@src/styles/global.css";

const openSans = Open_Sans({ subsets: ["cyrillic"] });

export const metadata = {
    title: "Marketplace Why We",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="ru">
            <Providers>
                <body className={openSans.className}>{children}</body>
            </Providers>
        </html>
    );
}
